version: "3.8"

services:
  web:
    depends_on:
      - api
    build: ./frontend
    ports:
      - 80:80

    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/pnpm-lock.yaml
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync

  api:
    build: ./backend
    ports:
      - 8000:8000

    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/pnpm-lock.yaml
          action: rebuild
        - path: ./backend
          target: /app
          action: sync
