name: Publish npm package

on:
  push:
    branches: [main]
    paths:
      - "packages/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
          cache-dependency-path: packages/package-lock.json

      - name: Installing dependencies
        working-directory: packages
        run: npm ci

      - name: Building package
        working-directory: packages
        run: npm run build

      - name: Publishing the package
        working-directory: packages
        run: npm publish --access public --provenance
